# consumes: KCLOUD_NAMESPACE RESULTS_PVC_NAME RESULTS_PVC_SIZE STORAGE_CLASS PVC_ACCESS_MODE RELEASE MANAGED_BY PART_OF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${RESULTS_PVC_NAME}
  namespace: ${KCLOUD_NAMESPACE}
  labels:
    app.kubernetes.io/managed-by: ${MANAGED_BY}
    app.kubernetes.io/part-of: ${PART_OF}
    app.kubernetes.io/name: ${RELEASE}
spec:
  storageClassName: ${STORAGE_CLASS}
  accessModes:
    - ${PVC_ACCESS_MODE}
  resources:
    requests:
      storage: ${RESULTS_PVC_SIZE}
