apiVersion: v1
kind: Service
metadata:
  name: kcloud-monitor
  labels:
    app: kcloud-monitor
spec:
  type: ClusterIP
  selector:
    app: kcloud-monitor
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
