apiVersion: npu.ai/v1alpha1
kind: NPUClusterPolicy
metadata:
  name: npuclusterpolicy-sample
spec:
  detector:
    image: 129.254.202.88:5100/npu-detector:1.0
  nvidia:
    enabled: true
    devicePluginImage: nvcr.io/nvidia/k8s-device-plugin:v0.17.1
    nodeSelector:
      nvidia.com/gpu.present: "true"
  furiosa:
    enabled: true
    devicePluginImage: ghcr.io/furiosa-ai/k8s-device-plugin:0.10.1
    configMapName: npu-device-plugin
    nodeSelector:
      furiosa: "true"
